let heroData = [
   {
      id: 1,
      logo: <><span className="hidden"></span></>,
      title: 'iPhone 14 Pro',
      subTitle: 'Pro. Beyond.',
      description: <><span className="hidden"></span></>,
      titleColor: 'text-white',
      link: 'https://www.apple.com/in/iphone-14-pro/',
      buttonLink1: 'https://www.apple.com/in/iphone-14-pro/',
      buttonLink2: 'https://www.apple.com/in/shop/goto/buy_iphone/iphone_14_pro',
      button1Text: <>Learn more <span> &gt;</span></>,
      button2Text: <>Buy <span> &gt;</span></>,
      small: 'bg-iphone14prosmall',
      medium: 'bg-iphone14promedium',
      large: 'bg-iphone14prolarge',
      style: 'h-[520px] xl:h-[580px]',
      titleStyle: 'text-4xl md:text-5xl xl:text-6xl',
      subTitleStyle: 'text-xl',
      descStyle: 'text-lg text-gray-500 ',
      buttonStyles: 'text-lg'
   },
   {
      id: 2,
      logo: <><span className="hidden"></span></>,
      title: 'iPhone 14',
      subTitle: 'Big and bigger.',
      description: <>iPhone 14 Plus available starting from 7 October</>,
      titleColor: 'text-black',
      link: 'https://www.apple.com/in/iphone-14/',
      buttonLink1: 'https://www.apple.com/in/iphone-14/',
      buttonLink2: 'https://www.apple.com/in/shop/goto/buy_iphone/iphone_14',
      button1Text: <>Learn more <span> &gt;</span></>,
      button2Text: <>Pre-Order <span> &gt;</span></>,
      small: 'bg-iphone14small',
      medium: 'bg-iphone14medium',
      large: 'bg-iphone14large',
      style: 'bg-cover h-[520px] xl:h-[580px] my-4',
      titleStyle: 'text-4xl md:text-5xl xl:text-6xl',
      subTitleStyle: 'text-xl',
      descStyle: 'text-lg text-gray-500 ',
      buttonStyles: 'text-lg'
   },
   {
      id: 3,
      logo: <><span className="hidden"></span></>,
      title: 'AirPods Pro',
      subTitle: 'Rebuilt from the sound up.',
      description: 'Available starting from 23 September',
      titleColor: 'text-white',
      link: 'https://www.apple.com/in/airpods-pro/',
      buttonLink1: 'https://www.apple.com/in/airpods-pro/',
      buttonLink2: 'https://www.apple.com/in/shop/goto/product/MQD83',
      button1Text: <>Learn more <span> &gt;</span></>,
      button2Text: <>Pre-Order <span> &gt;</span></>,
      small: 'bg-airpodsprosmall',
      medium: 'bg-airpodspromedium',
      large: 'bg-airpodsprolarge',
      style: 'bg-cover h-[520px] xl:h-[580px] my-4',
      titleStyle: 'text-4xl md:text-5xl xl:text-6xl',
      subTitleStyle: 'text-xl',
      descStyle: 'text-lg text-gray-500 ',
      buttonStyles: 'text-lg'
   },
]

export default heroData;