let promoData = [
   {
      id: 1,
      logo: <><i className="fa-brands fa-apple"></i></>,
      title: <>WATCH</>,
      subTitle: 'SERIES 8',
      description: <>A healthy leap ahead.</>,
      titleColor: 'text-white',
      link: 'https://www.apple.com/in/apple-watch-series-8/',
      buttonLink1: 'https://www.apple.com/in/apple-watch-series-8/',
      buttonLink2: 'https://www.apple.com/in/shop/goto/buy_watch/apple_watch_series_8',
      button1Text: <>Learn more <span> &gt;</span></>,
      button2Text: <>Buy <span> &gt;</span></>,
      small: 'bg-watchseries8small',
      medium: 'bg-watchseries8medium',
      large: 'bg-watchseries8large',
      style: 'h-[540px] xl:h-[580px]',
      titleStyle: 'text-5xl font-semibold',
      subTitleStyle: 'text-xl text-red-600 font-semibold',
      descStyle: 'text-lg text-gray-500 ',
      buttonStyles: 'text-lg'
   },
   {
      id: 2,
      logo: <><i className="fa-brands fa-apple"></i></>,
      title: 'WATCH',
      subTitle: 'SE',
      description: 'A great deal to love.',
      titleColor: 'text-black',
      link: 'https://www.apple.com/in/apple-watch-se/',
      buttonLink1: 'https://www.apple.com/in/apple-watch-se/',
      buttonLink2: 'https://www.apple.com/in/shop/goto/buy_iphone/iphone_14',
      button1Text: <>Learn more <span> &gt;</span></>,
      button2Text: <>Buy <span> &gt;</span></>,
      small: 'bg-watchsesmall',
      medium: 'bg-watchsemedium',
      large: 'bg-watchselarge',
      style: 'bg-cover h-[540px] xl:h-[580px]',
      titleStyle: 'text-5xl font-semibold',
      subTitleStyle: 'text-lg text-orange-600 font-semibold',
      descStyle: 'text-lg text-gray-500 ',
      buttonStyles: 'text-lg'
   },
   {
      id: 3,
      logo: <><i className="fa-brands fa-apple"></i></>,
      title: <>WATCH</>,
      subTitle: <><span className="text-yellow-400 text-base"> ULTRA</span> <br /> <span>Adventure awaits.</span></>,
      description: 'Available starting from 23 September',
      titleColor: 'text-black',
      link: 'https://www.apple.com/in/airpods-pro/',
      buttonLink1: 'https://www.apple.com/in/airpods-pro/',
      buttonLink2: 'https://www.apple.com/in/shop/goto/product/MQD83',
      button1Text: <>Learn more <span> &gt;</span></>,
      button2Text: <>Order now <span> &gt;</span></>,
      small: 'bg-watchultrasmall',
      medium: 'bg-watchultramedium',
      large: 'bg-watchultralarge',
      style: 'bg-cover h-[540px] xl:h-[580px]',
      titleStyle: 'text-5xl font-semibold',
      subTitleStyle: 'text-lg font-semibold',
      descStyle: 'text-lg text-gray-500 ',
      buttonStyles: 'text-lg'
   },
   {
      id: 4,
      logo: <><span className="hidden"></span></>,
      title: <><span className="italic" >Get supercharged for university.</span></>,
      subTitle: <>Last chance to get AirPods.<a className="hover:text-blue-500" href="#note2"><sup>2</sup></a></>,
      description: <><span className="text-pink-600 font-semibold" >Offer ends on 22 Sep</span></>,
      titleColor: 'text-black',
      link: 'https://www.apple.com/in/airpods-pro/',
      buttonLink1: 'https://www.apple.com/in/airpods-pro/',
      buttonLink2: 'https://www.apple.com/in/shop/goto/product/MQD83',
      button1Text: <><span className="hidden"></span></>,
      button2Text: <>Shop now <span> &gt;</span></>,
      small: 'bg-btssmall',
      medium: 'bg-btsmedium',
      large: 'bg-btslarge',
      style: 'bg-cover h-[540px] xl:h-[580px]',
      titleStyle: 'text-4xl font-semibold px-20 xl:px-40',
      subTitleStyle: 'text-xl',
      descStyle: 'text-lg text-gray-500 ',
      buttonStyles: 'text-lg'
   },
   {
      id: 5,
      logo: <><span className="hidden"></span></>,
      title: 'Macbook Air',
      subTitle: <>Supercharged by <i className="fa-brands fa-apple"></i>  M2</>,
      description: <><span className="hidden"></span></>,
      titleColor: 'text-black',
      link: 'https://www.apple.com/in/airpods-pro/',
      buttonLink1: 'https://www.apple.com/in/airpods-pro/',
      buttonLink2: 'https://www.apple.com/in/shop/goto/product/MQD83',
      button1Text: <>Learn more <span> &gt;</span></>,
      button2Text: <>Buy <span> &gt;</span></>,
      small: 'bg-macbookairsmall',
      medium: 'bg-macbookairmedium',
      large: 'bg-macbookairlarge',
      style: 'bg-cover h-[540px] xl:h-[580px]',
      titleStyle: 'text-5xl font-semibold',
      subTitleStyle: 'text-xl',
      descStyle: 'text-lg text-gray-500 ',
      buttonStyles: 'text-lg'
   },
   {
      id: 6,
      logo: <><span className="hidden"></span></>,
      title: <>iPad Air</>,
      subTitle: 'Light. Bright. Full of might.',
      description: <><span className="hidden"></span></>,
      titleColor: 'text-white',
      link: 'https://www.apple.com/in/ipad-air/',
      buttonLink1: 'https://www.apple.com/in/ipad-air/',
      buttonLink2: 'https://www.apple.com/in/shop/goto/buy_ipad/ipad_air',
      button1Text: <>Learn more <span> &gt;</span></>,
      button2Text: <>Buy <span> &gt;</span></>,
      small: 'bg-ipadairsmall',
      medium: 'bg-ipadairmedium',
      large: 'bg-ipadairlarge',
      style: 'bg-cover h-[540px] xl:h-[580px]',
      titleStyle: 'text-5xl font-semibold',
      subTitleStyle: 'text-xl',
      descStyle: 'text-lg text-gray-500 ',
      buttonStyles: 'text-lg'
   },
]

export default promoData;